blueprint:
  name: Turn on light at dusk
  description: Turn on a light at dusk
  domain: automation
  input:
    target_light:
      name: Light
      description: The light to turn on
      selector:
        entity:
          domain: light

trigger:
  platform: sun
  event: sunset
  offset: -00:30:00
    
condition:
  condition: numeric_state
  entity_id: !input target_light
  value_template: '{% if state.state == "on" %}{{ state.attributes.brightness }}{% else %}0{% endif %}'
  below: 1

action:
  data:
    brightness: 255
    entity_id: !input target_light
  service: light.turn_on
